directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
publish:
  provider: github
  owner: likelikeli
  token: <stripped sensitive data>
  private: true
  repo: zx07069352
  url: 'https://github.com/likelikeli/download/'
win:
  icon: ./public/icon.ico
mac:
  icon: ./public/Icon.icns
productName: 804所数据分析-轻翼
electronVersion: 9.2.0
